services:
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  backend:
    build: backend
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:latest"

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: